<div class="head">
    <img class="img-head"
         src="<?= STATIC_URL ?>/preview/img/basico128/title.jpg">
</div>
<!-- <div class="taxes">
        <div class="text_item_ml">
                NAVEGA POR INTERNET en tu celular a solo S/.0.49 el MB. <a
                        href="go.php?link=tarifas.php">Ver más</a>
        </div>
</div>-->


<div class="spance-line"></div>

<div class="banner">



    <?php foreach (array(1, 2, 3, 4, 5, 6) as $i) : ?>
        <div  class="item-banner">
            <div class="">
                <div class="flexslider">
                    <ul class="slides">
                        <?php foreach ($this->SoapBanners[$i] as $item): ?>
                            <li>
                                <a href="<?= $item['enlace'] ?>"><img class="img-banner" src="<?= DINAMIC_URL ?>banners/basico128/<?= $item['nombre'] ?>" alt="<?= $item['alt'] ?>" /></a>
                            </li>
                        <?php endforeach; ?>       
                    </ul>
                </div>
            </div>
        </div>
    <?php endforeach; ?>      

</div>
<div id="section">   
    <div class="title-list">
        <div class="title-item">Servicios</div>
    </div>
    <div class="spance-line-item"></div>


    <?php foreach ($this->SoapServicio as $item): ?>
        <div class="list">
            <a class="list-link" href="<?= $item['url'] ?>"> 
                <?= $item['descripcion'] ?>
            </a>
        </div>
    <?php endforeach; ?>


</div>

<!-- música -->
<div id="section">   
    <div class="title-list">
        <div class="title-item">Musica</div>
    </div>
    <div class="title-clic">(Dando clic en la canción ya estás comprando! Costo S/. 6.78 )</div>
    <div class="spance-line-item"></div>

    <?php foreach ($this->SoapMusica as $item): ?>
        <div class="list">
            <a class="list-link"
               href="<?= $item["url"] ?>"><?= $item["titulo"] ?>
            </a>
        </div>
    <?php endforeach; ?>

</div>

<!-- section -->
<div id="section">   
    <div class="title-list">
        <div class="title-item">Juegos</div>
    </div>
    <div class="title-clic">(Dando clic al juego ya estás comprando! Costo S/. 7.91)</div>
    <div class="spance-line-item"></div>
    
    <?php foreach ($this->SoapJuego as $item): ?>
        <div class="list">
            <a class="list-link"
               href="<?= $item["url"] ?>"><?= $item["nombre"] ?>
            </a>
        </div>
    <?php endforeach; ?>
</div>



<div class="banner-second-section">
    <?php foreach (array(7, 8) as $i) : ?>
        <div  class="item-banner">
            <div class="flex-container">
                <div class="flexslider">
                    <ul class="slides">
                        <?php foreach ($this->SoapBanners[$i] as $item): ?>
                            <li>
                                <a href="<?= $item['enlace'] ?>"><img class="img-banner" src="<?= DINAMIC_URL ?>banners/basico128/<?= $item['nombre'] ?>" alt="<?= $item['alt'] ?>" /></a>
                            </li>
                        <?php endforeach; ?>       
                    </ul>
                </div>
            </div>
        </div>
    <?php endforeach; ?> 
</div>

<!-- otros -->
<div id="section">
    <div class="spance-line-item"></div>    
     <?php foreach ($this->SoapText as $item): ?>
        <div class="list">
            <a class="list-link" href="<?= $item['enlace'] ?>">
                <?= $item['descripcion'] ?>
            </a>
        </div>
    <?php endforeach; ?>
</div>

<div class="banner-second-section">
    
    
     <?php foreach (array(9, 10) as $i) : ?>
            <div  class="item-banner">
                <div class="flex-container">
                    <div class="flexslider">
                        <ul class="slides">
                            <?php foreach ($this->SoapBanners[$i] as $item): ?>
                                <li>
                                    <a href="<?= $item['enlace'] ?>"><img class="img-banner" src="<?= DINAMIC_URL ?>banners/basico128/<?= $item['nombre'] ?>" alt="<?= $item['alt'] ?>" /></a>
                                </li>
                            <?php endforeach; ?>       
                        </ul>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    
    
</div>


