<div class="head">
    <img class="img-head"
         src="<?= STATIC_URL ?>preview/img/basico360/title.jpg">
</div>
<!-- <div class="taxes">
        <div class="text_item_ml">
                NAVEGA POR INTERNET en tu celular a solo S/.0.49 el MB. <a
                        href="go.php?link=tarifas.php">Ver más</a>
        </div>
</div>--> 


<div class="spance-line"></div>

<div class="banner">
    <?php foreach (array(1, 2, 3, 4, 5, 6) as $i) : ?>
        <div  class="box2">
            <div class="flex-container">
                <div class="flexslider">
                    <ul class="slides">
                        <?php foreach ($this->SoapBanners[$i] as $item): ?>
                            <li>
                                <a href="<?= $item['enlace'] ?>"><img class="img-banner" src="<?= DINAMIC_URL ?>banners/basico360/<?= $item['nombre'] ?>" alt="<?= $item['alt'] ?>" /></a>
                            </li>
                        <?php endforeach; ?>       
                    </ul>
                </div>
            </div>
        </div>
    <?php endforeach; ?> 
</div>
<div style="clear: both;"></div>



<div id="section">
    <div class="title-list">
        <div class="title-item">Servicios</div>
        <div style="clear: both;"></div>
    </div>
    <div class="spance-line-item"></div>

    <?php foreach ($this->SoapServicio as $item): ?>
        <div class="list">
            <a class="list-link" href="<?= $item['url'] ?>"> 
                <?= $item['descripcion'] ?>
            </a>
        </div>
    <?php endforeach; ?>
</div>


<!-- música -->
<div id="section">   
    <div class="title-list">
        <div class="title-item">Musica</div>
        <div class="title-clic">(Dando clic en la canción ya estás comprando! Costo S/. 6.78 )</div>
        <!--        <div class="view-plus">
                <a class="" href="#vermas">
                <img class="img-plus" src="<?= MEDIA_URL ?>/img/portalwap/basico360/icono_flecha.png">
                </a>
                </div>        -->
    </div>

</div>
<div class="spance-line-item"></div>
<table class="artist-photo">
    <tr>



        <?php foreach ($this->SoapMusica as $item): ?>
            <td class="artist">
                <div class="artist-text">
                    <div class="forma">
                        <img class="img-icono"
                             src="<?= DINAMIC_URL ?>musica/basico360/<?= $item["img"] ?>">
                    </div>
                    <div class="title-img">
                        <a class="text-title"
                           href="<?= $item["url"] ?>"><?= $item["titulo"] ?>
                        </a>
                    </div>
                </div>
            </td>
        <?php endforeach; ?>    
    </tr>  
</table>
<!-- section -->
<div id="section">   
    <div class="title-list">
        <div class="title-item">Juego</div>
        <div class="title-clic">(Dando clic al juego ya estás comprando! Costo S/. 7.91)</div>
        <!--        <div class="view-plus">
                <a class="" href="#vermas">
                <img class="img-plus" src="<?= MEDIA_URL ?>/img/portalwap/basico360/icono_flecha.png">
                </a>
                </div>        -->
    </div>

</div>
<div class="spance-line-item"></div>
<table class="artist-photo">
    <tr>

        <?php foreach ($this->SoapJuego as $item): ?>
            <td class="artist">
                <div class="artist-text">
                    <div class="">
                        <img class="img-icono"
                             src="<?= DINAMIC_URL ?>juego/basico360/<?= $item["img"] ?>">
                    </div>
                    <div class="title-img">
                        <a class="text-title"
                           href="<?= $item["url"] ?>"><?= $item["nombre"] ?>
                        </a>
                    </div>
                </div>
            </td>
        <?php endforeach; ?>
    </tr>  
</table>



<div class="banner-second-section">


    <?php foreach (array(7, 8) as $i) : ?>
        <div  class="box2">
            <div class="flex-container">
                <div class="flexslider">
                    <ul class="slides">
                        <?php foreach ($this->SoapBanners[$i] as $item): ?>
                            <li>
                                <a href="<?= $item['enlace'] ?>"><img class="img-banner" src="<?= DINAMIC_URL ?>banners/basico360/<?= $item['nombre'] ?>" alt="<?= $item['alt'] ?>" /></a>
                            </li>
                        <?php endforeach; ?>       
                    </ul>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
<div style="clear: both;"></div>



<?php foreach ($this->SoapText as $item): ?>
    <div class="center list-other box">
        <a class="list-link2" href="<?= $item['enlace'] ?>">
            <?= $item['descripcion'] ?>
        </a>
    </div>
<?php endforeach; ?>




<div class="banner-second-section">
    <?php foreach (array(9, 10) as $i) : ?>
        <div  class="box2">
            <div class="flex-container">
                <div class="flexslider">
                    <ul class="slides">
                        <?php foreach ($this->SoapBanners[$i] as $item): ?>
                            <li>
                                <a href="<?= $item['enlace'] ?>"><img class="img-banner" src="<?= DINAMIC_URL ?>banners/avanzado/<?= $item['nombre'] ?>" alt="<?= $item['alt'] ?>" /></a>
                            </li>
                        <?php endforeach; ?>       
                    </ul>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>


