<h3 class="admin-title"><?php echo $this->element->getView()->titulo?></h3>
<?php $this->getMesseger();?>
<div class="ctn-back">
    <a title="Volver al listado de Banners" href="/admin/banner">« Volver al listado de Banners</a>
</div>
<div class="frm-panel">

    <form id="frm-article" action="<?php echo $this->element->getView()->action?>" 
          method="post" Enctype="multipart/form-data">
        
        <div class="control-group">
            <label class="control-label" for="posicion">Posición:</label>
            <div class="controls">
                <?php echo $this->element->posicion; ?>
                 <?php echo $this->element->idbanner; ?>
            </div>
	</div>
         <div class="control-group">
            <label class="control-label" for="avanzado">Imagen Avanzado (320x96):</label>
            <div class="controls">
                <?php echo $this->element->avanzado; ?>
            </div>
            
	</div>
         <div class="control-group">
            <label class="control-label" for="basico128">Imagen basico128 (128x26):</label>
            <div class="controls">
                <?php echo $this->element->basico128; ?>
            </div>
	</div>
        
         <div class="control-group">
            <label class="control-label" for="basico240">Imagen basico240 (240x48):</label>
            <div class="controls">
                <?php echo $this->element->basico240; ?>
            </div>
	</div>
          <div class="control-group">
            <label class="control-label" for="basico360">Imagen basico360 (180x54):</label>
            <div class="controls">
                <?php echo $this->element->basico360; ?>
            </div>
	</div>
        
        <div class="control-group">
            <label class="control-label" for="Descripción">Descripción:</label>
            <div class="controls">
                <?php echo $this->element->descripcion; ?>
            </div>
	</div>
        <div class="control-group">
            <label class="control-label" for="Enlace">Enlace:</label>
            <div class="controls">
                <?php echo $this->element->enlace; ?>
            </div>
	</div>
        <div class="control-group">
            <label class="control-label" for="Alt">Alt:</label>
            <div class="controls">
                <?php echo $this->element->alt; ?>
            </div>
	</div>
        <div class="control-group">
            <label class="control-label" for="estado">Estado:</label>
            <div class="controls">
                <?php echo $this->element->estado; ?>
            </div>
	</div>
        
	<div class="control-group last">
            <div class="control">
                <button class="btn-admin" type="submit"><?php echo $this->element->getView()->submit?></button>
            </div>
	</div>
   </form>
</div>


 <div id="Layer1" style=" padding: 1em 3em; width:955; height:1000;margin: 1em 25%;float:left">
        <iframe src="http://local.adminwap/preview?perfil=2" 
                marginwidth="0" marginheight="0" name="ventana_iframe" scrolling="yes" border="0" 
                frameborder="0" width="300" height="400">
        </iframe>
    </div>